apiVersion: batch/v1
kind: Job
metadata:
  name: example-2-restart-onfailure
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: main
        image: busybox
        command: ["ls", "unvalid path"]
      restartPolicy: OnFailure
  backoffLimit: 2
