apiVersion: batch/v1
kind: Job
metadata:
  generateName: example-4-infinity-generatename-
  namespace: default
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sleep", "infinity"]
      restartPolicy: Never
  backoffLimit: 2
