apiVersion: batch/v1
kind: Job
metadata:
  generateName: example-4-fail-generatename-
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: main
        image: busybox
        command: ["ls", "unvalid path"]
      restartPolicy: Never
  backoffLimit: 2
