apiVersion: batch/v1
kind: CronJob
metadata:
  name: example-7-cronjob-infinity
  namespace: default
spec:
  schedule: "* * * * *"
  timeZone: "Asia/Seoul"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: busybox
            command: ["sleep"]
            args: ["infinity"]
          restartPolicy: OnFailure
