apiVersion: batch/v1
kind: Job
metadata:
  generateName: example-4-fail-generatename-presync-
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: main
        image: busybox
        command: ["ls", "unvalid path"]
      restartPolicy: Never
  backoffLimit: 2
